/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Autenticação - Locate-Family-Connect
 * Documentação do endpoint de autenticação/login usando PKCE com Supabase Auth.

 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  LoginResponse
} from '.././';




  /**
 * Realiza o login seguro do usuário utilizando o fluxo PKCE.

 * @summary Login do usuário (PKCE)
 */
export const postAuthLogin = <TData = AxiosResponse<LoginResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/login`,
      loginRequest,options
    );
  }
export type PostAuthLoginResult = AxiosResponse<LoginResponse>
