/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Autenticação - Locate-Family-Connect
 * Documentação do endpoint de autenticação/login usando PKCE com Supabase Auth.

 * OpenAPI spec version: 1.0.0
 */
import type { LoginRequestCodeChallengeMethod } from './loginRequestCodeChallengeMethod';

export interface LoginRequest {
  email: string;
  password: string;
  code_challenge: string;
  code_challenge_method: LoginRequestCodeChallengeMethod;
}
