/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Autenticação - Locate-Family-Connect
 * Documentação do endpoint de autenticação/login usando PKCE com Supabase Auth.

 * OpenAPI spec version: 1.0.0
 */
import type { UserProfile } from './userProfile';

export interface LoginResponse {
  access_token?: string;
  refresh_token?: string;
  user?: UserProfile;
}
