/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Autenticação - Locate-Family-Connect
 * Documentação do endpoint de autenticação/login usando PKCE com Supabase Auth.

 * OpenAPI spec version: 1.0.0
 */

export type UserProfileUserType = typeof UserProfileUserType[keyof typeof UserProfileUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserProfileUserType = {
  student: 'student',
  guardian: 'guardian',
  admin: 'admin',
} as const;
