/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Autenticação - Locate-Family-Connect
 * Documentação do endpoint de autenticação/login usando PKCE com Supabase Auth.

 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileUserType } from './userProfileUserType';

export interface UserProfile {
  id?: string;
  email?: string;
  user_type?: UserProfileUserType;
  created_at?: string;
}
