openapi: 3.0.0
info:
  title: Locate Family Connect API
  version: 1.0.0
  description: API documentation for Locate Family Connect application
  contact:
    email: support@sistema-monitore.com.br
servers:
  - url: https://rsvjnndhbyyxktbczlnk.supabase.co/rest/v1
    description: Supabase Production Server
paths:
  /profiles:
    get:
      summary: Get user profiles
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
          description: Filter by user ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
    post:
      summary: Create a new profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '201':
          description: Profile created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
  /guardians:
    get:
      summary: Get guardian relationships
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: student_id
          schema:
            type: string
          description: Filter by student ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Guardian'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Profile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        full_name:
          type: string
        phone:
          type: string
        user_type:
          type: string
          enum: [student, parent, guardian, developer]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Guardian:
      type: object
      properties:
        id:
          type: string
          format: uuid
        student_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        phone:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
