// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usnrnaxpoqmojxsfcoox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbnJuYXhwb3Ftb2p4c2Zjb294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4ODk0NTMsImV4cCI6MjA1MDQ2NTQ1M30.aaQ8gDyJS20GSr6AdjJN6gLJBEX7sTlPC3h8e06j_5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);